#macro FLOAT_BATTLE_PLAYER_PREPARE_TIMER 3
#macro INT_BATTLE_DEFAULT_TURN_COUNTDOWN 1

#macro FLOAT_BATTLE_HERO_LOCATION_X 400
#macro FLOAT_BATTLE_ENEMY_LOCATION_X 1200
#macro FLOAT_BATTLE_HERO_LOCATION_Y 400
#macro FLOAT_BATTLE_ENEMY_LOCATION_Y 400
#macro FLOAT_BATTLE_HERO_SEPERATION_X 125
#macro FLOAT_BATTLE_HERO_SEPERATION_Y 125
#macro FLOAT_BATTLE_ENEMY_SEPERATION_X 125
#macro FLOAT_BATTLE_ENEMY_SEPERATION_Y 125
#macro FLOAT_BATTLE_ENEMY_DIAGONAL_SEPERATION_FACTOR 1.25

#macro INT_HITBOX_DIMENSION 64

#macro INT_BATTLE_POINTER_VERT_OFFSET 15
#macro INT_BATTLE_POINTER_RANDOM 12

enum int_battle_state
{
	NOT_BATTLING = -1,
	BATTLE_INITIALIZE = 0,
	BATTLE_PLAYER_PREPARE = 1,
	BATTLE_PLAYING = 2,
	BATTLE_PAUSED = 3,
	BATTLE_ENDING = 4
}

enum int_Moves
{
	BASIC_ONE = 0,
	BASIC_TWO = 1,
	BASIC_THREE = 2,
	BASIC_FOUR = 3,
	BASIC_FIVE = 4,
	
	ABILITY_ONE = 5,
	ABILITY_TWO = 6,
	ABILITY_THREE = 7,
	ABILITY_FOUR = 8,
	ABILITY_FIVE = 9,
	
	ULTIMATE = 10,
	GUARD = 11,
	FLEE = 12
}

//For enemy AI
enum int_BE_CurrentMoveArray
{
	MOVE_IDENTIFIER = 0,
	WEIGHT = 1,
	USABLE = 2
}

//For Battle Menus
enum int_BattleMenu_Buttons
{
	ATTACK = 0, 	
	GUARD = 1,
	ITEMS = 2, 
	ULTIMATE = 3,
	FLEE = 4,
	BASIC = 0,
	ABILITIES = 1
}

enum int_BattleMenu_ArrayPositions
{
	OWNER = 0,
	CURRENT_STRUCT = 1,
	BASIC = 2,
	ABILITIES = 3,
	ITEMS = 2,
	ULTIMATE = 2
}

enum int_TypeOfTargeting 
{
	ALLY_SELECTIVE = 0,
	ALLY_SELF = 1,
	ALLY_PARTY = 2,
	ALLY_RANDOM = 3,
	ALLY_SPECIFIC = 4,
	ENEMY_SELECTIVE = 5,
	ENEMY_AREA = 6,
	ENEMY_PARTY = 7,
	ENEMY_RANDOM = 8,
	ENEMY_SPECIFIC = 9
}

#macro INT_BATTLE_NUMBER_OF_MOVES 5