#macro FLOAT_DEFAULT_WAIT_CHOICE_WAIT 3

#macro INT_TEXTBOX_DEFAULT_X_POS 10
#macro INT_TEXTBOX_DEFAULT_WIDTH 1580
#macro INT_TEXTBOX_DEFAULT_Y_POS 465
#macro INT_TEXTBOX_DEFAULT_HEIGHT 425

#macro INT_TEXT_DEFAULT_RELATIVE_X 70
#macro INT_TEXT_DEFAULT_RELATIVE_Y 100
#macro INT_TEXT_DEFAULT_WIDTH 1480
#macro INT_TEXT_DEFAULT_Y_OFFSET 40

#macro INT_CHOICE_DEFAULT_X 400
#macro INT_CHOICE_DEFAULT_WIDTH 800
#macro INT_CHOICE_DEFAULT_HEIGHT 120
#macro INT_CHOICE_DEFAULT_VERTICAL_OFFSET 10
#macro INT_CHOICE_DEFAULT_TEXT_WIDTH 760
#macro INT_CHOICE_DEFAULT_TEXT_RELATIVE_Y 10

#macro INT_CHOICE_DEFAULT_ONE_MIDDLE_Y 210

#macro INT_CHOICE_DEFAULT_TWO_1_MIDDLE_Y (INT_CHOICE_DEFAULT_ONE_MIDDLE_Y - INT_CHOICE_DEFAULT_VERTICAL_OFFSET / 2 - INT_CHOICE_DEFAULT_HEIGHT / 2)
#macro INT_CHOICE_DEFAULT_TWO_2_MIDDLE_Y (INT_CHOICE_DEFAULT_ONE_MIDDLE_Y + INT_CHOICE_DEFAULT_VERTICAL_OFFSET / 2 + INT_CHOICE_DEFAULT_HEIGHT / 2)

#macro INT_CHOICE_DEFAULT_THREE_1_MIDDLE_Y (INT_CHOICE_DEFAULT_ONE_MIDDLE_Y - INT_CHOICE_DEFAULT_VERTICAL_OFFSET - INT_CHOICE_DEFAULT_HEIGHT)
#macro INT_CHOICE_DEFAULT_THREE_2_MIDDLE_Y (INT_CHOICE_DEFAULT_ONE_MIDDLE_Y)
#macro INT_CHOICE_DEFAULT_THREE_3_MIDDLE_Y (INT_CHOICE_DEFAULT_ONE_MIDDLE_Y + INT_CHOICE_DEFAULT_VERTICAL_OFFSET + INT_CHOICE_DEFAULT_HEIGHT)

#macro INT_CHOICE_DEFAULT_FOUR_1_MIDDLE_Y (INT_CHOICE_DEFAULT_TWO_1_MIDDLE_Y - INT_CHOICE_DEFAULT_VERTICAL_OFFSET - INT_CHOICE_DEFAULT_HEIGHT)
#macro INT_CHOICE_DEFAULT_FOUR_2_MIDDLE_Y INT_CHOICE_DEFAULT_TWO_1_MIDDLE_Y
#macro INT_CHOICE_DEFAULT_FOUR_3_MIDDLE_Y INT_CHOICE_DEFAULT_TWO_2_MIDDLE_Y
#macro INT_CHOICE_DEFAULT_FOUR_4_MIDDLE_Y (INT_CHOICE_DEFAULT_TWO_2_MIDDLE_Y + INT_CHOICE_DEFAULT_VERTICAL_OFFSET + INT_CHOICE_DEFAULT_HEIGHT)

#macro FLOAT_SELECTED_SIZE_INCREASE 1.2

enum int_DefaultChoice
{
	TEXT = 0,
	METHOD = 1,
	TYPESPEED = 2,
	TEXTBOX_SPRITE = 3,
	FONT = 4, 
	TEXT_SCALE = 5,
	DELAY = 6,
	INSTANT_TYPE = 7,
	TEXT_CENTERED = 8
}

enum int_text_effect
{
	OUTLINE_WHITE = 0,
	OUTLINE_BLACK = 1,
	OUTLINE_BLEND = 2,
	OUTLINE_WHITE_PULSE = 3,
	OUTLINE_BLACK_PULSE = 4,
	OUTLINE_BLEND_PULSE = 5,
	ARROW_LEFT = 6,
	YELLOW_TEXT = 7,
}


#macro TRIGGER_PLACEHOLDER_FONT_TOP_OFFSET 25

#macro INT_CLEAR_MENU -1
